title: Jake's Blog
description: The home of Jake's musings
email: jake@stride.me.uk
twitter_username: jake
url: https://jakestride.com
permalink: /posts/:year/:month/:day/:title:output_ext
excerpt_separator: <!-- readmore -->
host: 0.0.0.0
author:
  twitter: jake
  picture: /assets/images/favicon.png
collections:
  links:
    output: false
sass:
    sass_dir: _sass
plugins:
  - jekyll-feed
feed:
  disable_in_development: true
  categories:
    - links
    - Featured
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      is_page: "agaga"
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/gems/
