title: Jake's Blog
email: jake@stride.me.uk
twitter_username: jake
url: https://jake.stride.me.uk
permalink: /posts/:year/:month/:day/:title:output_ext
excerpt_separator: <!-- readmore -->
collections:
  - links
sass:
    sass_dir: _sass
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "posts"
  -
    scope:
      path: ""
      type: "pages"
    values:
      is_page: "agaga"
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/